### PR TITLE
Support for RN>=0.25

### PR DESCRIPTION
**Pull request by mat2maa**
Tested with RN 0.26.2.

### CODE REVIEW

**Comment by alvaromb** [comment]
👍 will merge today!

Thanks @mat2maa!

**Comment by alvaromb** [comment]
Can you separate the following commits and make another PR?

I don't want to merge the RN>=25 support with the other changes.

**Comment by mat2maa** [comment]
Apologies, I thought you had already merged. I've split of my changes into a separate repo and force pushed a reset back to the relevant commit on this fork.

**Comment by alvaromb** [comment]
Sorry @mat2maa 😢 

I didn't have time to do it on Friday, apologies.

**Comment by mat2maa** [comment]
:smile: No worries @alvaromb, thanks for the useful component!

**Comment by alvaromb** [comment]
Merged and published https://github.com/APSL/react-native-floating-label/releases/tag/v0.2.2

**Pull request merged**
